name: Terraform Dev Deployment

# on:
#   push:
#     paths:
#       - 'terraform/**'
#     branches:
#       - main
#   pull_request:
#     paths:
#       - 'terraform/**'
#     branches:
#       - main

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Apply (Dev)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/environments/dev

    env:
      TF_VAR_auth0_provider_client_id: ${{ secrets.AUTH0_CLIENT_ID }}
      TF_VAR_auth0_provider_client_secret: ${{ secrets.AUTH0_CLIENT_SECRET }}
      TF_VAR_auth0_domain: ${{ secrets.AUTH0_DOMAIN }}
      AWS_REGION: "us-east-1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Empty S3 bucket before destroy
        run: aws s3 rm s3://hello-world-webapp-prod --recursive

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform destroy
        if: github.ref == 'refs/heads/main'
        run: terraform destroy -auto-approve
        
